fos_rest:
  view:
    view_response_listener:  true
  format_listener:
    rules:
    - { path: '^/', prefer_extension: true, fallback_format: json, priorities: [ json ] }
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  exception:
    exception_controller: 'fos_rest.exception.controller:showAction'
    codes:
      Doctrine\ORM\EntityNotFoundException: 404
      \LogicException: 400
      \DomainException: 400
    messages:
      Doctrine\ORM\EntityNotFoundException: true
      \LogicException: true
      \DomainException: true
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: validationErrors
