language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

notifications:
   on_success: never
   on_failure: always