language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

deploy:
  provider: heroku
  api_key:
    secure: W0oJMMyaMiJ80BHZtSvEgdQXW32fL4BjT0QoRoEXwu9BkRxHESxq36ohFzR25U9oqfzHx1vqZnGFPmn4h3ly4vZH6QilW8bFTSzue7acbDro2cQybWIp04mq9wfd7IjhyYUG3UFi0/c3k91869XlQx0i3bVWzw2NRo8zi37Wm7uFv/dHZ8F4qp7H57/aeEKm36/eod44LOeD1zz4jNluHK59pWFEahAlIzAzWtniLUKsV5dFUE25d2ZQShTLrj39F/ZVP4xHY4y3KpmnAuiNuiRMhDb+RQRK6UdPUqUSF5+bclla9t/dLm0DonRsF2ptBW4c5X6Eup9fV6/0/JbK4B3X1lS1F31HPmUy96tTr9AhgwfnvU+CkJC+EmUtj5jvLev2f1D8UHKI5h5tVGm1CuZK0XUtXCFK3de0vqD+dNajRaqtpnourXvIF3fn88HVqy4heEO0eChyri+Bzf4vz4UqJCvPWY0u/5sLGVH/UYEtUeePiNHYh2qk9tA0R773xJQKbl14F7Iv4+w+uvQQMy5m8xqYS0V4Baf735OdH+cmWp7VJ5gtLsw03YLoARFHplbjXdI3lI4fL0JDAXGfMKiroR29i2L2AgOOEE4UlK1qSB1adGczYALB9i9iPFbwTlYg+DU89wVFUBHER1/ONeUOh5cAh0UC4r9AqzgErt8=
  app: bfh-webshop-backend
  on:
    repo: janfriedli/bfh-webshop-backend

notifications:
   on_success: never
   on_failure: always