language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

deploy:
  provider: heroku
  api_key:
    secure: ffkFbVsOcSbEmaWcjV1+MNAiNrYsQ42uX4RYubo4aKhgspT+aZebz1qfNUlWjiO2Ch2R8rsdibLCd3NIHnV635rZs9mxKMbPf3UgrFfmZjPqhnI9CN0TZ5nSvoPExiJxAjUP9M/zL7Bs0ItF4VZ+qHMJ3ZJTzjYqIjRPJLIY54bIQ3HH5cue6rbJvaHdYjsR3b9cZAj+4LEVXBnDX+8grFOFb5VzHLf77DrU6n1BeTmfyw5jMTOmSG1ChlIIpJnprVW2Tv9kA6xffd2YKQ9tX8CBXZAxuURGf8rJWplm9VPkFjV8waqrXWVH7x8mCr7oPpWmIItYqlk3UWT8sVdhBZbZmKW+FjoKndmxtc9ahSPS+ths972eqBmrlt3Wq8eljmQLC8MCUYyKwVVu1Up2BYBy3E1SsOPlPwBTpYUT3bsO1d5458WdC7IrnOGzpvbUcAl9V5fEkaFW1IoRRE+L6jcVEDqwUDSL72xEogrtR3+CBpk4byur7lwFMXkmw1sIV0O1uHy+clArn67p9PyHQgZdGIOWh83KIYyt6YnbYEy4saN+kq4Y3V7Pik2VuSbkMZNYxD74gntEXh3c+9iFoximKyuBp1umlUTZxLiJeywt7375y+L+heLrahibKihA9C1lvDEzgmDkJCbCWI3V77uNu5cMz28rHb3QqCJ9gNI=
  app: bfh-webshop-backend
  on:
    repo: janfriedli/bfh-webshop-backend

notifications:
   on_success: never
   on_failure: always