language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

deploy:
  provider: heroku
  api_key:
    secure: JvMQbMZ80oVcXu1jyMtzl7SRYNF2k3WORX8h6iLMgSltuIPU0rsNR67W+MQQDVHuwcWNOTxty+lBVSf5iY0G3VcKmqW7Gic1BDZrWmRfivNwB3dBNfH5w0twFXCejiSGxna8KUpxsc+kJy1o6KC2KPlZiZIbA4ptXwgUpxWhkbfBiByx0mAfvVJzkfjSd1oIufoGDglJTXFywf3QgEAlOoW2mgSO6fq6AEVTXTgaVW6Sjvhl5ckHonFtC6N5tehZSKLMS9Fdv2GgrGxC7uMv+IOiE5jdKng2SrPkRGTELZhJIcrMN4cDMY6V87SS37ItQlwwyxTx6XEBZI8sZTuUaclP/CzQfVkCwiBywyi/03w2Jw+b0yKLl2wsyGi+LhPhXjECMAcnIaCtMJxdalbJiYoVQxD+lOG2pHhonS8R6vTish6xf/R/KKgDeLN0UQM9MwRMqUcdk1wMPpLNJW232aW4Ocr2Ru63k+7NrLdEtAxa+NwSt8kQSRj3YcMVgtuFl6MMvLdVuOQ5rG1/KkNBt+Ewjj3sNAD30wFfaMJdZxn1pALTHVb1y5Nx2LT+4Riyiv2R15VtixHeUkxdQqMpBHzPc2gPTmWpU+XpRlHRcbrWtGa9MTHbR81fpnODNGSRcheAUuLr+Lanvvs7lbVNmJYMHJBjDShsbJFGOzSOwXc=

# Customize when the notification emails are sent.
notifications:
   on_success: never
   on_failure: always