language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

deploy:
  provider: heroku
  api_key:
    secure: fqHlf0KuhdbPPf8eIQzN60O581dTChKgdXqCRYW8m9DU3Pz5iQbKyV9mKUgePLOafF63s1siAnT86FKIKl4oU3GoTWVzj2noFSum+NTWkpdV1o0eQlkBPdgKZ6hMDTStbhpsWB1X8zU3dG8UvkKDTpLsgfmUmbXCeXZllZplFqMUbd5Sn8lk5UZ4WSM/IkarYqOt+4NEIDbwB1FoaWt+tdOj/Avoi85EBXx5wYwU/ml8w2wki521oRJVzaS1Bxd/N2HyG1hnJbtX7HamFWgbSVE+BZncuqcfnLNK5hZ+ba+vMRFEBFjlTYsQPtOuXSr+mksdD9acfdYDlNM3eHpUUOprbLu2CCjQ9vfAavHJNcF4HS+c7cdO8FFqQqBebUCEcLNWWiZrqUpUyxZFXAhO/bBzZZbxB0cQDJXZN0Y6Y607BEGlHA4Wd0epU6CMPDuUcJHxOKE0Ps3pz1f7PaVlhC2sNKbPJrEc5n4sMs+3lHr5E8Pqz+GFijqTC99JDwK+LzEZw6fcInjVJINzOIpAo6C5+G6YBTqiXt2ZDkavpKJdJ8adC/4HIzDqIleiBVmK6lFGTOGZy9pbiEoexF047GiL0nlSufRCXSqcDxM8iz/0VSv4062JWoQLDila6FJSYlnf4iDpffE523LtWOJhjAVfwF1uYJDFfEDdTtnVNbQ=
  app: bfh-webshop-backend
  on:
    repo: janfriedli/bfh-webshop-backend

notifications:
   on_success: never
   on_failure: always