language: php
php:
  - '7.1'
  - '7.2'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction

script: phpunit

matrix:
 allow_failures:
   - php: nightly
 fast_finish: true

deploy:
  provider: heroku
  api_key:
    secure: RfG+SkkYscUa9sk5f2wEWVjfjb2WlbZuvR7Oi4IzM2Dib3+i/IrLv5qd+HnhT2N/d1YjMLYs2EqZlt6pafqoETQdnXAbvK0lpzBufFsl8vrTrbTXcd4sLDUQiJZweLUrdYr6i3qStTfYeV0nRF1z/5DJWg3iaCrAdV0FjAhknUhfLgZLik8i0EFLfS8K/J1XrJ+/sEpqbPKWcgWwd2Z4LBAlj5k1E6T5ADXA1Rgtzw2MsE2KDZWvLEXtNXqyRz/Dt+TGtpXgGyUIHFCYu3OrNRI3U0T7XeU1wKTA1xE4s0AsqK3W/qfNkzOQjwlxT1Rsxg5NxL4xH0zsKeaoOX0h98xUiAAFKCIEnoVsW8FV2jkl7AV108Pdfi/npxk+21qZ2/MwNA4cJDWdGDEbIqRXej3kqt8bekGMj4x9AEt0SlPhFpHmUZ6Zx+ToIm6n8kKjeCVc7ddwwE5KuPdS5y286twFY8Wc1Y3AqOXKQN/6gkFMXS9KnU2P8HKsxFNKttIyLoe7bZ/3KlVHi7226v4YSXz6oA+eVgILdQnxjqQkOFqlOj9JeXDbibZjorLtF7oD2jRv72krQNcYVMhqAuoaVm2dfUhmmFV+fl25+VkakNByElIH4vjMrfMFIi4DjOhTG3uXpx/jo+OgX0/Ocj5OxZK/VJXJsDNnvY3io2LjTHk=
  app: bfh-webshop-backend
  on:
    repo: janfriedli/bfh-webshop-backend

notifications:
   on_success: never
   on_failure: always